stages:
  preprocess_train:
    cmd: python src/data/preprocess.py data/raw/yellow_tripdata_2026-01.parquet data/processed/train.parquet
    deps:
      - src/data/preprocess.py
      - data/raw/yellow_tripdata_2026-01.parquet
    outs:
      - data/processed/train.parquet

  preprocess_validation:
    cmd: python src/data/preprocess.py data/raw/yellow_tripdata_2026-02.parquet data/processed/test.parquet
    deps:
      - src/data/preprocess.py
      - data/raw/yellow_tripdata_2026-02.parquet
    outs:
      - data/processed/test.parquet